services:
  - docker

language: python

dist: trusty
sudo: false
cache:
  pip: true

python:
  - "3.6"

branches:
  except:
    - gh-pages

git:
  depth: 1

env:
  global:
  - secure: ovjTxvdJBaJir11IEvvPY5kTugW4JTQ0+1ryK8VhTYpU3nUaqe1sHgoJR3EmtWZ4vBXeHYAqdNTg0vzg828YxT4kTyEH8LccIuqRXl0qg4IejKImm4VIUg7g9FPUxNdz1F3ydTa+svTMxJdVUPd36yCVqHa1j79xGyUl5rC7MZEnAEw8uPF+dz50PkJEDmYxgM2txM6w5EbHHqmRQ3/zZHpc1UxTLheFQEwR/oWLyMepQSWoh8wWTZvaHiiWWRHvh96HSX/h5AaqruEUe7h9e0jhVbkHsuDJcvLfSg0fF21rs61HMfgzYPpHeM+eWo2AAilE7yXdzn+r+omoTIHpbj1F26JqfHFt8CG2vZYrNkeFVpJjFC5cS17zrZV536/8X5RLi5ZTJBiF5ucR4u616sCoBi/OaIcI5z2zcWw1BK7ZYhvwcNY5jGmslsKj99VGtHLZ1Qm9bS+LZmKaBDWhor5F2NOrfBz3WFjekPXc37EjDdoValmrUM6nmlQERi6STgdD5Ugf6koakY95i5K8LAxogy02FN8iCf3THYOilU0AEiBFrgGUXd/chOcXAG7pMNRkE1b+6CcDLnibGVUldvTLtX88Rov/xnv/ZoX14qBQqL89AErYTd1wRswqH4CbYmCQXXNN88IVTXII5hGv5ydPrdo+tyumjB4cYGHvquU=
  - BUILD_TESTING=$( [[ ${TRAVIS_REPO_SLUG} =~ qgis/pyqgis ]] && [[ ${TRAVIS_EVENT_TYPE} != pull_request ]] && [[ ${TRAVIS_BRANCH} =~ ^master$ ]] && echo "false" || echo "true" )

matrix:
  include:
    - env: QGIS_VERSION_BRANCH=master

script:
  - ./scripts/ci/run-docker.sh
